<?php 

error_reporting(0);
error_reporting(E_ALL & ~E_NOTICE);


define('E',FALSE);

define('_codeword','abc');

define('_ShowAds',FALSE);

define('_PPStitle','PsyPlan ZodiacEvents');
define('_PPStitleTM','<b>PsyPlan<sup><sup><font size=1>TM</font></sup></sup> ZodiacEvents<sup><sup><font size=1>TM</font></sup></sup></b>');

define('_FontFaceSansSerif','Arial, Helvetica, sans-serif');
define('_FontFaceHeading','Verdana, Arial, Helvetica, sans-serif');
define('_FontFaceZodiac','ZodiacJaDy');








define('_accountalreadyexists','account already exists');
define('_Address','Address');
define('_Advanced','Advanced');
define('_AdvancedChoices','time/location coordinates for more accurate transits,<br>and choice of House System and Succinct Implications Database');
define('_AJAXneeded','Either XMLHttpRequest, Msxml2.XMLHTTP or Microsoft.XMLHTTP AJAX service is needed.');
define('_Allowemailfrom','Allow email <i>from</i>');
define('_AlreadyamemberShallIemailyourpassword','Already a member? Shall I email your password?');
define('_AM','AM');
define('_and','and');
define('_Anemailwelcomemessagewillbesenttoyouwith','An email welcome message will be sent to you with');
define('_AnotherDate','AnotherDate');
define('_ApplyChangesAbove','ApplyChangesAbove');
define('_applyDASHing','apply-<br>ing');
define('_applying','applying');
define('_AreBeingLoaded','are being loaded.');
define('_Aspect','Aspect');
define('_Aspects','ASPECTS');
define('_atCity','at');
define('_AtlasQuery','<a target="atlas" href="http://www.astro.com/cgi-bin/atlw3/aq.cgi?lang=e">Astrodienst - Atlas Query</a>.');
define('_Automatic','Automatic');
define('_Availablebysubscriptionpennyapage','Available by subscription - penny a page.');
define('_AWeekofClassicPsyPlan','A Week of Classic PsyPlan');
define('_browserUnable','Your browser is unable to use this facility and/or JavaScript is disabled.');
define('_BACK','BACK');
define('_BackToDirectory','BACK to Directory.');
define('_Backup','Backup');
define('_Biorhythms','BIORHYTHMS');
define('_BirthCity','birth city');
define('_BirthDate','Birth Date');
define('_Birthplace','Birthplace');
define('_BirthTime','Birth time');
define('_born','born');
define('_BuildEmptyHolidays','build an empty HOLIDAYS');
define('_BuildEmptySID','build an empty SID');
define('_BuildNewDatabaseNamed','Build a new database named');
define('_BuildNewHolidaysListNamed','Build a new Holidays List named');
define('_built','built');
define('_BuyMorePages','buy more pages');
define('_BuyMorePagesNow','BUY MORE PAGES NOW');
define('_CalendarPages','calendar pages');
define('_CantFindYour',"Can't find your");
define('_CityStateCountry','city, state/country');
define('_Classic','Classic');
define('_ClassicPocketPsyPlan','Classic Pocket PsyPlan');
define('_ClassicPsyPlanDailyPlanner','Classic PsyPlan Daily Planner');
define('_ClassicPsyPlanPlanners','Classic PsyPlan Planners');
define('_Click','Click');
define('_ClickAdate','Click a date for another day.');
define('_ClickIfBlank','Click here if image is blank.');
define('_Clickonbuymorepagestoincrease','Click on "buy more pages" to increase.');
define('_Clickparametertomakeanothersimilar','<i> Click <b>parameter</b> to make another similar. </i>');
define('_Clicktitletoviewreport','<i> Click <b>title</b> to view report. </i>');
define('_ClickAutomaticStartDate','click here to automatically set the Start Date<br>to the date of the first day of the next month after today or after the day<br>whenever the bookmarked/favorites page is loaded');
define('_CookieDeleted','The ZodiacEvents cookie has been deleted.');
define('_Continued','Continued');
define('_CopyAnotherHOLIDAYS','copy from another HOLIDAYS');
define('_CopyAnotherSID','copy from another SID');
define('_Current','Current');
define('_CurrentLocation','current location');
define('_DailyCharts','DailyCharts');
define('_Daily_Charts','Daily Charts');
define('_DailyPlanner','DailyPlanner');
define('_Daily_Planner','Daily Planner');
define('_DailyTransits','DailyTransits');
define('_Daily_Transits','Daily Transits');
define('_Date','Date');
define('_day','day');
define('_DaylightSavingsTimeQ','Daylight Savings Time?');
define('_Declination','Declination');
define('_DeleteMarkedItems','delete<br>marked<br>items');
define('_Detail','Detail');
define('_DidStoreChanges','Did you store your changes using');
define('_DontKnow',"If you don't know, enter");
define('_DoBackup','DoBackup');
define('_DoneBackup','Done backup copy of your');
define('_DoneRestore','Done restore from backup of your');
define('_DoneSave','Done saving changes to your');
define('_DoRestore','DoRestore');
define('_EDIT','EDIT');
define('_Edit_Cities','Edit Cities');
define('_EditHolidays','EditHolidays');
define('_Edit_Holidays','Edit Holidays');
define('_Edit_Holidays_List','Edit Holidays List');
define('_EditSID','EditSID');
define('_EditSuccinctImplicationsDatabase','Edit Succinct Implications Database');
define('_EditYourPrivateDatabase','Edit your private database');
define('_EditYourPrivateHOLIDAYS','edit your private HOLIDAYS');
define('_EditYourPrivateHolidaysList','Edit your private Holidays List');
define('_EditYourPrivateSID','edit your private SID');
define('_Emailaddress','Email address');
define('_EnterNameNewHOLIDAYS','Enter a name for your new HOLIDAYS.');
define('_EnterNameNewSID','Enter a name for your new SID.');
define('_Ephemeris','Ephemeris');
define('_ExactApplyingSeparating','exact today is <b>bold</b>, applying is <font color=blue>blue</font>, separating is <font size=1>tiny</font>');
define('_example','example');
define('_find','find');
define('_firsttoreportafaultearns1000pages','first to report a fault earns 1000 pages.');
define('_for','for');
define('_ForPrinting','For printing see ');
define('_GET','GET');
define('_Give10tothestudentdonationfund','Give $10 to the student donation fund');
define('_HavePrinter',"If you have a printer it's easy to print this yourself.");
define('_HalfHour','Half hour');
define('_HELP','HELP');
define('_here','here');

define('_HintEnterJustCityStateCountry','<b>Hint:</b> Enter just <i>city</i>, <i>state</i> or <i>country</i> alone.');
define('_HOLIDAYS','HOLIDAYS');
define('_HolidayName','Holiday Name');
define('_HolidaysNotNamed','The Holidays List is not named.');
define('_HolidaysTitle','HOLIDAYS Title');
define('_hour','hour');
define('_House','House');
define('_HouseSystem','House System');
define('_HowToPrintThis','How To Print This');
define('_HowToReadThis','How To Read This');
define('_HowToUseThis','How To Use This');
define('_IdeasHere','Ideas here');
define('_Ifyoudontallowcookiessignin','If you don\'t allow cookies, sign-in');
define('_in',' in ');
define('_InAboveList','in the above list.');
define('_InOurAtlas','it in our atlas.<br>You may use a nearby city.<br>Or, look it up in the');
define('_isNowShared','is now shared for others to use.');
define('_isRed','is red');
define('_Itsthecountofavailablepages','It\'s the count of available pages.');
define('_JOIN','JOIN');
define('_Joinnow100pagesfreenoobligation','Join now - 100 pages free - no obligation.');
define('_Latitude','Latitude');

define('_Location','Location');
define('_LocationZone','Location and time zone');
define('_Longitude','Longitude');
define('_LunarPlanner','LunarPlanner');
define('_Lunar_Planner','Lunar Planner');
define('_maydrawonthedonationfundnow','may draw on the donation fund (now $');
define('_membersonly','members only');
define('_minute','minute');
define('_MoonPhases','MOON PHASES');
define('_MonthlyPlanner','MonthlyPlanner');
define('_Monthly_Planner','Monthly Planner');
define('_mustbeavalid','must be a valid');
define('_NameAlreadyTaken','That name is already taken.');
define('_NameOnReport','Name on report');
define('_Natal','Natal');
define('_NatalPlanetPositions','Natal Planet Positions');
define('_NegativePageCount','WARNING - NEGATIVE PAGE COUNT - ');
define('_NEXT','NEXT');
define('_No','No');
define('_noon','noon');
define('_NoteOnceShared','<b>Note:</b> Once shared, your database cannot be un-shared except with help from Psychic Planner Inc. technical support services.<br>&mdash;<br>Note: Even when shared, only you can make changes to your database.');
define('_NoteOnlyFiveBackups','<b>Note:</b> Only the five most-recent backups for each database are maintained.');
define('_NoteWillReplace','<b>Note:</b> This operation will completely replace your');
define('_Noticethenumberintopleftcorner','Notice the number in top-left corner.');
define('_of','of');
define('_OKAY','OKAY');
define('_OneHour','One hour');
define('_OneLunarMonthofClassicPsyPlan','One Lunar Month of Classic PsyPlan');
define('_OneMonthofClassicPsyPlan','One Month of Classic PsyPlan');
define('_or','or');
define('_OrpickfromamongMakeAnotherbelow','Or, pick from among MakeAnother below.');
define('_parameter','parameter');
define('_Password','Password');
define('_Planet','Planet');
define('_Planets','Planets');
define('_PlanetsAndPoints','PLANETS AND POINTS');
define('_PleaseStart','Please start');
define('_PleaseWaitWhile','Please wait while');
define('_PM','PM');
define('_PocketPlanner','PocketPlanner');
define('_Pocket_Planner','Pocket Planner');
define('_Positionsoftheplanets','Positions of the planets');
define('_Print','Print');
define('_PrintingServices','We can provide printing services. Email your request to <a href=mailto:jgd@psyplan.com>jgd@PsyPlan.com</a>.');
define('_ProblemComputing','There was a problem with the computing');
define('_Precessed','Precessed');
define('_Print','Print');
define('_ProceedIgnore','Proceed and IGNORE your changes?');
define('_PysPlanForcastsUseWisely','&nbsp; PsyPlan forecasts your planets transits.<br>&nbsp; You alone are responsible for your life.<br>&nbsp; Please use with wisdom.');
define('_PublicDirectory','Public Directory');
define('_QuickGuide','Quick Guide');
define('_ReadySaveBackup','Ready to save a backup copy of your');
define('_RememberSIGNINwithacookie','Remember SIGN-IN (with a cookie).');
define('_Reportproblems','Report problems');
define('_Restore','Restore');
define('_SampleDirectory','Sample Directory');

define('_SaveToDatabase','SaveToDatabase');

define('_ScrollDown','Please scroll down.');
define('_SelectBackup','Select a backup copy to replace your');
define('_separating','separating');
define('_separDASHating','separ-<br>ating');
define('_ShallIemailyourpassword','Shall I email your password?');
define('_Share','Share');
define('_Sign','Sign');
define('_SIGNIN','SIGN-IN');
define('_StartDate','Start Date');
define('_Starthere','Start here');
define('_Studentsandothersunabletopay','Students and others unable to pay');
define('_SuccinctImplicationsDatabase','Succinct Implications Database');
define('_Summary','Summary');
define('_Timeline','Timeline');
define('_TimeZone','Zone');
define('_TimeZoneConverted','Time zone -- Converted to numeric value and E/W.');
define('_TimeShownDST','Times shown are Daylight Saving Time');
define('_title','title');
define('_today','today');
define('_todeletemarkedreports','to delete marked reports');
define('_tomakeanothersimilar','to make another similar');
define('_tomorrow','tomorrow');
define('_Tools','Tools');
define('_Transit','Transit');
define('_Transiting','Transiting');
define('_TransitingAspects','Transiting Aspects');
define('_TransitingPlanetPositions','Transiting Planet Positions');
define('_UnDo','UnDo');
define('_UnknownUseNoon','If unknown, please use 12:00 pm');
define('_UseLettersNumbersUnderscore','Use only letters, numbers and the underscore');
define('_UsePrecession','Use precession of the zodiac (0.0138 degrees per year)');
define('_Usage','Usage');
define('_Weekdays2letter','SU MO TU WE TH FR SA');
define('_WeeklyPlanner','WeeklyPlanner');
define('_Weekly_Planner','Weekly Planner');
define('_Welcome','Welcome');
define('_Wesendemailonlyuponspecificrequestsfromyou','We send email only upon specific requests from you.');
define('_Whatshere','What\'s here');
define('_year','year');
define('_YES','YES');
define('_yesterday','yesterday');
define('_YouCanBookmark','You can bookmark/favorites this page.');
define('_YouMayCloseWindow','You may close this window now.');
define('_Your','Your');
define('_YourDirectoryIsEmpty','Your Directory is EMPTY, so pick from among "Make another" below.');
define('_YourNewDatabaseCopyOf','Your new database may be a<br>copy of one of these databases');
define('_YourNewHolidaysCopyOf','Your new Holidays List may be a<br>copy of one of these Holidays Lists');
define('_Yourpersonaldailycharts','Your personal daily charts');
define('_Yourpersonaldailyhoroscope','Your personal daily horoscope');
define('_yourpasswordNomoneynow100pagesfree','your password. No money now - 100 pages free.');
define('_Youremailaddress','Your email address');
define('_YourDirectory','Your Directory');
define('_zap','zap');

define('_ZodiacSigns','ZODIAC SIGNS');
define('_zone','zone');



define('_HelpSID_GET0','Or click the BACK or NEXT button to move through the implication selections.');
define('_HelpSID_GET1','Select a transit planet, an aspect and a natal planet, then click the GET button.');
define('_HelpSID_GET2','Your selection will appear in the text box where you can edit the implication.');
define('_HelpSID_BACK','Get the previous implication.');
define('_HelpSID_NEXT','Get the next implication.');
define('_HelpSID_UnDo','Un-do changes that were applied with the last use of the EDIT button.');
define('_HelpSID_EDIT','Apply your changes to this implication.');

define('_HelpSID_Save','Apply all changes to the database. The UnDo button will now no longer un-do changes.');
define('_HelpSID_Backup','Save the contents of your succinct implication database, typically for use as a backup.');
define('_HelpSID_Restore','Load to your succinct implication database the contents of a backup file built using the Backup button.');
define('_HelpSID_Print','This will open a new window with all readings in your succinct implication database. Appropriate for printing.');
define('_HelpSID_Share','You can share your succinct implication database with others.');



define('_body','body');
define('_mind','mind');
define('_soul','soul');
define('_strong','strong');
define('_critical','critical');
define('_adagio','adagio');

define('_new_moon','new moon');
define('_waxing_moon','waxing moon');
define('_full_moon','full moon');
define('_waning_moon','waning moon');
define('_void_of_course','void-of-course');

define('_NewMoon','A new cycle. Projects begun now reflect sober reasoning with favorable results.');
define('_WaxingMoon','Problems remain from the previous cycle. Accept feedback and adjust plans.');
define('_FullMoon','Projects begun at new moon are made public and may be fulfilled or thwarted. Consolidate actions.');
define('_WaningMoon','A time for withdrawal. Handle loose ends and forgotten details. Get ready for new cycle.');

define('_mNa','Name -- We really need a name for the report.<br>Many people use just a first name.');
define('_mMo','Birth Month -- We really need the birth month to prepare a report.');
define('_mDa','Birth Day -- We really need the birth day to prepare a report.');
define('_mYr','Birth Year -- We really need the birth year to prepare a report.');
define('_mHr','Birth Hour -- We really need the birth hour to prepare a report.<br>If birth time is unknown, please use 12:00 PM (noon).');
define('_mMn','Birth Minute -- We really need the birth minute to prepare a report.<br>If birth time is unknown, please use 12:00 PM (noon).');
define('_mAm','Birth AM/PM -- We really need the birth am/pm to prepare a report.');
define('_mCi','Birth City -- We really need the birth city.');
define('_mSt','Birth State -- We really need the birth state to prepare a report.');
define('_mCCi','Current City -- We really need the current city.');
define('_mCSt','Current State -- We really need the current state to prepare a report.');
define('_mLz','Latitude-longitude-zone must be entered as a set.');
define('_mLt','Latitude -- Latitude has the format of ##N/S##.');
define('_mLg','Longitude -- Longitude has the format of ###E/W##.');
define('_mTz','Time-zone -- Please enter a valid time-zone number.');
define('_mPm','Report Month -- We really need the report month to prepare a report.<br>Or, select Automatic.');
define('_mPd','Report Day -- We really need the report day to prepare a report.<br>Or, select Automatic.');
define('_mPy','Report Year -- We really need the report year to prepare a report.<br>Or, select Automatic.');

define('_Months','month,January,February,March,April,May,June,July,August,September,October,November,December');

define('_AspectNames','Conjunct,Opposite,Trine,Trine,Square,Square,Sextile,Sextile');
define('_AspectWords','enhance,confront,favor,favor,strain,strain,support,support,burden');
define('_HouseWords','0,apparent,resourced,connected,domestic,enthused,service,partner,shared,academic,career,group,hidden');
define('_PlanetNames','Ascendant,Sun,Moon,Mercury,Venus,Mars,Jupiter,Saturn,Uranus,Neptune,Pluto,Midheaven');
define('_PlanetWords','persona,power,emotion,expression,affection,action,expansion,effort,freedom,impression,change,purpose');
define('_SignNames','Aries,Taurus,Gemini,Cancer,Leo,Virgo,Libra,Scorpio,Sagittarius,Capricorn,Aquarius,Pisces');
define('_SignWords','assertive,possessive,flexible,sensitive,dramatic,helpful,balanced,ardent,friendly,practical,creative,intuitive');

$PublicReport['George W. Bush|41N18,72W55,5W,19460706,726AM,New Haven, CT']='38N54,77W02,5W,00000000,Washington, DC|Koch';
$PublicReport['Al Gore|38N54,77W02,5W,19480331,1253PM,Washington, DC']='38N54,77W02,5W,00000000,Washington, DC|Koch';
$PublicReport['Hillary Rodham Clinton|41N51,87W39,6W,19471026,800AM,Chicago, IL']='38N54,77W02,5W,00000000,Washington, DC|Koch';
$PublicReport['Fred Thompson|34N46,87W42,5W,19420819,209PM,Sheffield, AL']='38N54,77W02,5W,00000000,Washington, DC|Koch';
$PublicReport['Joe Lieberman|41N03,73W32,5W,19420224,230AM,Stamford, CT']='38N54,77W02,5W,00000000,Washington, DC|Koch';
$PublicReport['Ned Lamont|38N54,77W02,5W,19540103,1200PM,Washington, DC']='38N54,77W02,5W,00000000,Washington, DC|Koch';


?>
